function Test1()
{
  TestedApps.Todos.Run();
  let microsoft_Todos = Aliases.Microsoft_Todos;
  let windows_UI_Core_CoreWindow = microsoft_Todos.Microsoft_To_Do;
  let landmarkTarget = windows_UI_Core_CoreWindow.PaneRoot.Sidebar.Sidebar;
  let button = landmarkTarget.New_list;
  button.Click();
  aqObject.CheckProperty(button.New_list, "Text", cmpEqual, "New list");
  let namedContainerAutomationPeer = landmarkTarget.Lists.Untitled_list_more_options_available.Untitled_list_more_options_available;
  let textBox = namedContainerAutomationPeer.Untitled_list_Rename_list;
  textBox.Keys("Teste[Enter]");
  namedContainerAutomationPeer.Click(116, 19);
  button.Click();
  textBox.Keys("testere[Down]");
  namedContainerAutomationPeer.Click(95, 23);
  let wnd = windows_UI_Core_CoreWindow.DetailAndTaskSplitView;
  let textBlock = wnd.K;
  textBlock.Click(14, 13);
  wnd.Add_a_task_in_testere_.Keys("dinesh");
  wnd.Add_due_date.Click();
  let wndXaml_WindowedPopupClass = microsoft_Todos.wndXaml_WindowedPopupClass;
  wndXaml_WindowedPopupClass.Click(105, 17);
  wnd.Add_a_reminder.Click();
  OCR.Recognize(microsoft_Todos.wndXaml_WindowedPopupClass2).BlockByText("today").Click();
  textBlock.Click(13, 7);
  let listView = wnd.Tasks;
  namedContainerAutomationPeer = listView.Task_dinesh_Due_Today_You_have_a_reminder_set_for_Today_at_19_00_more_options_available.Task_dinesh_Due_Today_You_have_a_reminder_set_for_Today_at_19_00_more_options_available;
  namedContainerAutomationPeer.Click(444, 32);
  let namedContainerAutomationPeer2 = wnd.PaneRoot.Details_for_task_dinesh;
  let scrollViewer = namedContainerAutomationPeer2.ScrollViewer;
  scrollViewer.Assign_to.Click();
  let scrollViewer2 = windows_UI_Core_CoreWindow.Pop_up_2.ContentScrollViewer;
  scrollViewer2.Create_invitation_link.Click();
  scrollViewer2.List_members.Dinesh_B_Owner_.Click(152, 27);
  aqObject.CheckProperty(Aliases.Microsoft_Todos.Microsoft_To_Do.DetailAndTaskSplitView.PaneRoot.Details_for_task_dinesh.ScrollViewer.Dinesh_B, "ObjectIdentifier", cmpEqual, "Dinesh_B");
  scrollViewer.Add_file.Click();
  let dlgOpen = Aliases.PickerHost.dlgOpen;
  dlgOpen.DUIViewWndClassName.Explorer_Pane.CtrlNotifySink.ShellView.Items_View.Capture.Click(41, 75);
  dlgOpen.btnOpen.ClickButton();
  textBox = scrollViewer.Add_note;
  OCR.Recognize(textBox.ContentElement).BlockByText("note").Click();
  textBox.Keys("Tester");
  scrollViewer.Click(84, 631);
  namedContainerAutomationPeer2.Dismiss_detail_view.Click();
  namedContainerAutomationPeer.Incomplete_task.Click();
  aqObject.CheckProperty(listView.Collapse_Completed_bucket.Collapse_Completed_bucket.Collapse_Completed_bucket.Completed, "Text", cmpEqual, "Completed");
  listView.Completed_task_dinesh_Due_Today_To_access_the_notes_attached_to_the_task_go_to_details_Files_attached_Assigned_to_Dinesh_B_more_options_available.Completed_task_dinesh_Due_Today_To_access_the_notes_attached_to_the_task_go_to_details_Files_attached_Assigned_to_Dinesh_B_more_options_available.ClickR(428, 35);
  OCR.Recognize(wndXaml_WindowedPopupClass).BlockByText("task").Click();
  scrollViewer2.Delete.Click();
  Aliases.ApplicationFrameHost.wndApplicationFrameWindow.Close();
}